name: Test Docker

on:
  push:
    branches: [ "branchHTTPserverMulti" ]
  pull_request:
    branches: [ "branchHTTPserverMulti" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/darynanahaivska:latest
          platforms: linux/amd64,linux/arm64

      - name: Run Docker container
        run: |
          docker run -d --name my_running_server -p 8081:8081 dnahaivska13/darynanahaivska:latest
          docker ps

