name: Test CI

on:
  push:
    branches: [ "branchHTTPserver" ]
  pull_request:
    branches: [ "branchHTTPserver" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtest-dev cmake automake autoconf

      - name: Build
        run: |
          aclocal
          autoconf
          automake --add-missing
          ./configure   
          cmake .              
          make               

      - name: Compile test_euler.cpp
        run: |
          g++ -o build/test_server test_euler.cpp
